services:
  blue-fox-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: blue-fox-global-group-ssr
    restart: unless-stopped
    networks:
      - infra-net

networks:
  infra-net:
    external: true