export const contactContent = {
  title: 'Get in Touch',
  subtitle: 'Have an idea, want to propose a partnership, or just chat? I\'m available.',
  partnershipTitle: 'Partnerships & Startups',
  partnershipDescription: 'Are you building a startup or have an idea that needs workforce to become reality? If I can help build a system, app, or tool, let\'s talk! I\'m open to collaborations and partnerships as a co-founder or developer.',
  partnershipCta: 'Send a Proposal',
  infoTitle: 'Contact Information',
  emailLabel: 'E-mail',
  emailValue: 'blue.fox.group.contact@gmail.com',
  linkedinLabel: 'LinkedIn',
  linkedinValue: 'linkedin.com/in/felipeferraz4',
  linkedinUrl: 'https://www.linkedin.com/in/felipeferraz4/',
  reachLabel: 'Reach',
  reachValue: 'Brazil, United States, and Portuguese, English, and Spanish-speaking countries.',
  form: {
    nameLabel: 'Your Name',
    namePlaceholder: 'What should I call you?',
    nameErrorRequired: 'Name is required.',
    emailLabel: 'Your E-mail',
    emailPlaceholder: 'your@email.com',
    emailErrorRequired: 'E-mail is required.',
    emailErrorInvalid: 'Please enter a valid e-mail address.',
    subjectLabel: 'Subject',
    subjectPlaceholder: 'e.g. Partnership, Project, Collaboration, Question',
    subjectErrorRequired: 'Subject is required.',
    messageLabel: 'Message',
    messagePlaceholder: 'Tell me about your idea or proposal...',
    messageErrorRequired: 'Message is required.',
    submitBtn: 'Send Message',
    submitBtnSending: 'Sending...',
    successTitle: 'Message Sent!',
    successMessage: 'Thank you for reaching out! I\'ll reply as soon as possible.',
    errorTitle: 'Error Sending',
    errorMessage: 'There was an issue sending your message. Please try again later.'
  }
};
