export const contactContent = {
  title: 'Contact Us',
  subtitle: 'Get in touch with our corporate relations and new business development team.',
  infoTitle: 'Global Headquarters',
  addressLabel: 'Main Address',
  addressValue: '1000 Paulista Ave - Bela Vista, São Paulo - SP, Brazil',
  phoneLabel: 'Phone',
  phoneValue: '+55 (11) 3214-5500',
  emailLabel: 'Corporate E-mail',
  emailValue: 'relations@bluefoxgg.com',
  hoursLabel: 'Office Hours',
  hoursValue: 'Monday to Friday, 9:00 AM to 6:00 PM (BRT)',
  form: {
    nameLabel: 'Full Name',
    namePlaceholder: 'Enter your full name',
    nameErrorRequired: 'Full name is required.',
    emailLabel: 'Business E-mail',
    emailPlaceholder: 'you@yourcompany.com',
    emailErrorRequired: 'E-mail is required.',
    emailErrorInvalid: 'Please enter a valid e-mail address.',
    subjectLabel: 'Subject',
    subjectPlaceholder: 'e.g. Partnerships, Investment Relations, New Business',
    subjectErrorRequired: 'Subject is required.',
    messageLabel: 'Message',
    messagePlaceholder: 'Please outline your request or inquiry...',
    messageErrorRequired: 'Message is required.',
    submitBtn: 'Send Message',
    submitBtnSending: 'Sending...',
    successTitle: 'Message Sent!',
    successMessage: 'Thank you for reaching out. Our relations team will respond within 24 business hours.',
    errorTitle: 'Error Sending',
    errorMessage: 'There was an issue sending your message. Please try again later.'
  }
};
