export const contactContent = {
  title: 'Fale Conosco',
  subtitle: 'Entre em contato com nossa equipe de relações corporativas e novos negócios.',
  infoTitle: 'Nossos Escritórios',
  addressLabel: 'Sede Principal',
  addressValue: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP, Brasil',
  phoneLabel: 'Telefone',
  phoneValue: '+55 (11) 3214-5500',
  emailLabel: 'E-mail Corporativo',
  emailValue: 'relations@bluefoxgg.com',
  hoursLabel: 'Horário de Atendimento',
  hoursValue: 'Segunda a Sexta, das 09h às 18h (BRT)',
  form: {
    nameLabel: 'Nome Completo',
    namePlaceholder: 'Digite seu nome completo',
    nameErrorRequired: 'O nome é obrigatório.',
    emailLabel: 'E-mail Profissional',
    emailPlaceholder: 'voce@suaempresa.com',
    emailErrorRequired: 'O e-mail é obrigatório.',
    emailErrorInvalid: 'Formato de e-mail inválido.',
    subjectLabel: 'Assunto',
    subjectPlaceholder: 'Ex: Parcerias, Novos Negócios, Relações com Investidores',
    subjectErrorRequired: 'O assunto é obrigatório.',
    messageLabel: 'Mensagem',
    messagePlaceholder: 'Descreva sua proposta ou dúvida...',
    messageErrorRequired: 'A mensagem é obrigatória.',
    submitBtn: 'Enviar Mensagem',
    submitBtnSending: 'Enviando...',
    successTitle: 'Mensagem Enviada!',
    successMessage: 'Agradecemos o contato. Nossa equipe de relações retornará em até 24 horas úteis.',
    errorTitle: 'Erro ao enviar',
    errorMessage: 'Ocorreu um problema ao enviar a mensagem. Por favor, tente novamente.'
  }
};
