export const contactContent = {
  title: 'Fale Comigo',
  subtitle: 'Tem uma ideia, quer propor uma parceria ou apenas trocar uma ideia? Estou à disposição.',
  partnershipTitle: 'Parcerias & Startups',
  partnershipDescription: 'Está construindo uma startup ou tem uma ideia que precisa de mão de obra para virar realidade? Se eu puder ajudar a construir um sistema, app ou ferramenta, vamos conversar! Estou aberto a colaborações e parcerias como sócio ou desenvolvedor.',
  partnershipCta: 'Enviar Proposta',
  infoTitle: 'Informações de Contato',
  emailLabel: 'E-mail',
  emailValue: 'blue.fox.group.contact@gmail.com',
  linkedinLabel: 'LinkedIn',
  linkedinValue: 'linkedin.com/in/felipeferraz4',
  linkedinUrl: 'https://www.linkedin.com/in/felipeferraz4/',
  reachLabel: 'Atuação',
  reachValue: 'Brasil, Estados Unidos e países de língua portuguesa, inglesa e espanhola.',
  form: {
    nameLabel: 'Seu Nome',
    namePlaceholder: 'Como posso te chamar?',
    nameErrorRequired: 'O nome é obrigatório.',
    emailLabel: 'Seu E-mail',
    emailPlaceholder: 'seuemail@exemplo.com',
    emailErrorRequired: 'O e-mail é obrigatório.',
    emailErrorInvalid: 'Formato de e-mail inválido.',
    subjectLabel: 'Assunto',
    subjectPlaceholder: 'Ex: Parceria, Projeto, Colaboração, Dúvida',
    subjectErrorRequired: 'O assunto é obrigatório.',
    messageLabel: 'Mensagem',
    messagePlaceholder: 'Conte-me sobre sua ideia ou proposta...',
    messageErrorRequired: 'A mensagem é obrigatória.',
    submitBtn: 'Enviar Mensagem',
    submitBtnSending: 'Enviando...',
    successTitle: 'Mensagem Enviada!',
    successMessage: 'Obrigado pelo contato! Vou responder o mais rápido possível.',
    errorTitle: 'Erro ao enviar',
    errorMessage: 'Ocorreu um problema ao enviar a mensagem. Por favor, tente novamente.'
  }
};
